#!/bin/bash

# variables
gitrepo=https://github.com/cudelreg/htmlappservicepage
webappname=curthtmlviaarmtemplate$RANDOM
resourcegroup=TestCurt-ARM$RANDOM

# Create a resource group.
az group create --location westus --name resourcegroup

# Create an App Service plan in Standard_GRS
az appservice plan create --name $webappname --resource-group $resourcegroup --sku Standard_GRS

# Create a web app.
az webapp create --name $webappname --resource-group $resourcegroup \
--plan $webappname

#Create a deployment slot called staging
az webapp deployment slot create --name $webappname --resource-group myResourceGroup \
--slot staging

# Deploy sample code to staging slot from GitHub.
az webapp deployment source config --name $webappname --resource-group $resourcegroup \
--slot staging --repo-url $gitrepo --branch master --manual-integration

# Copy the result of the following command into a browser to see the staging slot.
echo http://$webappname-staging.azurewebsites.net

# Swap the verified/warmed up staging slot into production.
az webapp deployment slot swap --name $webappname --resource-group $resourcegroup \
--slot staging

# Copy the result of the following command into a browser to see the web app in the production slot.
echo http://$webappname.azurewebsites.net
