#!/bin/bash

# variables
gitrepo=https://github.com/cudelreg/htmlappservicepage
webappname=curthtmlviaarmtemplate$RANDOM
resourcegroup=TestCurt-ARM$RANDOM

#clone giot repo where html file sits
git clone https://github.com/cudelreg/htmlappservicepage
cd htmlappservicepage

# Create a resource group.
az group create --location westus --name $resourcegroup
echo $resourcegroup

# Create an App Service plan with S1
az appservice plan create --name $webappname --resource-group $resourcegroup --sku S1
echo $webappname

# Create a web app.
# az webapp create --name $webappname --resource-group $resourcegroup \ --plan $webappname
az webapp up --location westus --name $webappname –html

#cleanup
cd ..
rm -rf htmlappservicepage


#Create a deployment slot called staging
az webapp deployment slot create --name $webappname --resource-group myResourceGroup \ --slot staging

# Deploy sample code to staging slot from GitHub.
az webapp deployment source config --name $webappname --resource-group $resourcegroup \ --slot staging --repo-url $gitrepo --branch master --manual-integration

# Copy the result of the following command into a browser to see the staging slot.
echo http://$webappname-staging.azurewebsites.net

# Swap the verified/warmed up staging slot into production.
az webapp deployment slot swap --name $webappname --resource-group $resourcegroup \
--slot staging

# Copy the result of the following command into a browser to see the web app in the production slot.
echo http://$webappname.azurewebsites.net
